### ISSUE TITLE
Update link and add COPYRIGHT

### ISSUE THREAD

**Issue by icaoberg** [pscedu/singularity-blast#7]
https://github.com/pscedu/singularity-blast/blob/7da15132b78ab8edb2f64ad496704b36f62396e8/2.9.0/Singularity#L7

Change the string `gitlab` to `github` and `icaoberg` to `pscedu`.

Also add `COPYRIGHT`.

**Comment by halbakri** [comment]
Successfully updated

**Comment by icaoberg** [comment]
Info was added by @halbakri
